name: Run All Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clean-build-test:
    runs-on: macos-latest

    steps:
    - name: Look for XCode
      run: ls -n /Applications/ | grep Xcode*
