name: Run All Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
   clean-build-test:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: CocoaPod Install
      run: pod install
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app && /usr/bin/xcodebuild -version
    - name: Run tests
      run: xcodebuild clean build test -workspace MobileShop.xcworkspace -scheme MobileShop -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.5,name=iPhone 13" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
